---
title: "final_report"
author: "Peter Menzies"
date: "25/01/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

* Intro - what is classes as a brain tumour, explain difference between malignant/non-malignant
        -   Looking at Scotland and it's health boards between 1994 and 2017
        - Investigating how the incidence, survival and mortality differs between healthboards and across the time span


* Incidence has increased slightly across scotland but no huge changes
* Incidence fairly consistent across health boards
* Increase likely due to aging population, we can expect further increases as our population ages.

* 1 year survival has improved a touch
* 5 year survival has not changed
* 10 year survival not reliably reported...perhaps due to being very low

* Difficulties - Main risk factors are age (fairly consitent across the country), family history (not available without individual patient records), obesity
              -   A less common cancer compared to lung/bone/liver with a less obvious trigger (eg. smoking/alcohol) so low numbers means difficulty providing statistically significant survival data.
              
* 

* Next steps:
  -   Data on different brain tumour classifications/ site/depth of tumour
  -   Data on stage at presentation
  -   Data on family history
  -   Data on symptoms/impact on QoL, particularly in those who survived long term
  -   Data stretching further back to see if introduction of MRI's increased reporting or survival rate
  -   Monitor impact of New laser therapy
  








