---
title: "maps"
author: "Peter Menzies"
date: "01/02/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=F, message=F}
source("cleaning_exploration_script.R")

library(sf)
library(rgdal)
library(rmapshaper)
```

```{r}
chunks <- readOGR(dsn = "data/SG_NHS_HealthBoards_2019", layer = "SG_NHS_HealthBoards_2019") %>% 
  st_as_sf()

hb_borders <- ms_simplify(chunks) %>% 
  select(HBCode, HBName, geometry) %>% 
  rename("Code" = "HBCode",
         "hb" = "HBName") %>% 
  mutate(hb = str_to_lower(hb))

unique(hb_borders$hb)

```

# Ages

```{r}
ages_map_data_2019 <- pop_2019_all_clean %>%
  mutate(hb = str_to_lower(hb)) %>% 
  left_join(hb_borders, by = "Code") %>% 
  rename(hb = hb.x) %>% 
  select(-hb.y)

ages_map_data_2017 <- pop_2017_all_clean %>%
  mutate(hb = str_to_lower(hb)) %>% 
  left_join(hb_borders, by = "hb") 

ages_map_data_1994 <- pop_1994_all_clean %>%
  mutate(hb = str_to_lower(hb)) %>% 
  left_join(hb_borders, by = "hb")


head(ages_map_data_2019)
head(ages_map_data_2017)
head(ages_map_data_1994)


```

```{r}
ages_map_data_2019 %>% 
  filter(over_65 == "over_65") %>% 
  ggplot() +
  geom_sf(aes(fill = percentage_pop, geometry = geometry)) +
  scale_fill_steps(
          limits = c(13, 26),
          high = "#132B43",
          low = "#56B1F7",
          space = "Lab",
          na.value = "grey50",
          guide = "coloursteps",
          aesthetics = "fill",
          labels = waiver(),
          show.limits = T) +
  scale_colour_manual(values = c("TRUE" = "#cca300", "FALSE" = NA)) +
  guides(colour = FALSE) +
  labs(fill = "Percent over 65",
        x = NULL,
        y = NULL,
       title = "Percentage of Population over 65, 2019") +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(size = 12))

ages_map_data_2017 %>% 
  filter(over_65 == "over_65") %>% 
  ggplot() +
  geom_sf(aes(fill = percentage_pop, geometry = geometry)) +
  scale_fill_steps(
          limits = c(13, 26),
          high = "#132B43",
          low = "#56B1F7",
          space = "Lab",
          na.value = "grey50",
          guide = "coloursteps",
          aesthetics = "fill",
          labels = waiver(),
          show.limits = T) +
  scale_colour_manual(values = c("TRUE" = "#cca300", "FALSE" = NA)) +
  guides(colour = FALSE) +
  labs(fill = "Percent over 65",
        x = NULL,
        y = NULL,
       title = "Percentage of Population over 65, 2017") +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(size = 12))

ages_map_data_1994 %>% 
  filter(over_65 == "over_65") %>% 
  ggplot() +
  geom_sf(aes(fill = percentage_pop, geometry = geometry)) +
  scale_fill_steps(
          limits = c(13, 26),
          high = "#132B43",
          low = "#56B1F7",
          space = "Lab",
          na.value = "grey50",
          guide = "coloursteps",
          aesthetics = "fill",
          labels = waiver(),
          show.limits = T) +
  scale_colour_manual(values = c("TRUE" = "#cca300", "FALSE" = NA)) +
  guides(colour = FALSE) +
  labs(fill = "Percent over 65",
        x = NULL,
        y = NULL,
       title = "Percentage of Population over 65, 1994") +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(size = 12))
```

# Incidence 

```{r}
incidence_map <- incidence_map_prep %>% 
  filter(value_type == "crude_rate") %>% 
  left_join(hb_borders, by ="hb") %>% 
  rename(code = Code.x) %>% 
  select(-Code.y)

incidence_region_map<- regional_incidence_map %>% 
  filter(sex == "all",
         cancer_type == "mal_brain_plus_glands",
         age == "all") %>% 
  left_join(hb_borders, by = "hb")
  
max(incidence_region_map$inc_region)
min(incidence_region_map$inc_region)

names(incidence_region_map)

head(incidence_region_map)

unique(incidence_map$sex)
```

```{r}
incidence_map %>% 
  filter(year == 2017,
         cancer_type == "all",
         sex == "all") %>% 
  ggplot() +
  geom_sf(aes(fill = value, geometry = geometry)) +
  scale_fill_steps(
          n.breaks = 7,
          high = "#132B43",
          low = "#56B1F7",
          space = "Lab",
          na.value = "grey50",
          guide = "coloursteps",
          aesthetics = "fill",
          labels = waiver(),
          show.limits = T) +
  scale_colour_manual(values = c("TRUE" = "#cca300", "FALSE" = NA)) +
  guides(colour = FALSE) +
  labs(fill = "Crude Rate",
        x = NULL,
        y = NULL,
       title = "Incidence, 2017") +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(size = 12))

incidence_map %>% 
  filter(year == 2000,
         cancer_type == "all",
         sex == "all") %>% 
  ggplot() +
  geom_sf(aes(fill = value, geometry = geometry)) +
  scale_fill_steps(
          n.breaks = 7,
          high = "#132B43",
          low = "#56B1F7",
          space = "Lab",
          na.value = "grey50",
          guide = "coloursteps",
          aesthetics = "fill",
          labels = waiver(),
          show.limits = T) +
  scale_colour_manual(values = c("TRUE" = "#cca300", "FALSE" = NA)) +
  guides(colour = FALSE) +
  labs(fill = "Crude Rate",
        x = NULL,
        y = NULL,
       title = "Incidence, 2000") +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(size = 12))


```

* Some correlation between ages over 65 and incidence, but shows there are other factors. 

* NA's for 1994 as data isnt reported 

```{r}
incidence_map %>% 
  filter(year == 1994,
         cancer_type == "mal_brain",
         sex == "all") %>% 
  ggplot() +
  geom_sf(aes(fill = value, geometry = geometry)) +
  scale_fill_steps(
          n.breaks = 7,
          high = "#132B43",
          low = "#56B1F7",
          space = "Lab",
          na.value = "grey50",
          guide = "coloursteps",
          aesthetics = "fill",
          labels = waiver(),
          show.limits = T) +
  scale_colour_manual(values = c("TRUE" = "#cca300", "FALSE" = NA)) +
  guides(colour = FALSE) +
  labs(fill = "Crude Rate",
        x = NULL,
        y = NULL,
       title = "Incidence, Malignant, 1994") +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(size = 12))

```



```{r}
# incidence_map %>% 
#   filter(year == 1994,
#          cancer_type == "mal_brain_plus_glands",
#          sex == "all") %>% 
#   ggplot() +
#   geom_sf(aes(fill = value, geometry = geometry)) +
#   scale_fill_distiller(
#           limits = c(5, 11),
#           palette = "YlOrRd",
#           direction = 1) +
#   guides(colour = FALSE) +
#   labs(fill = "Crude Rate",
#         x = NULL,
#         y = NULL,
#        title = "Incidence, region, Malignant plus glands, 1994") +
#   theme(axis.text = element_blank(),
#         axis.ticks = element_blank(),
#         panel.background = element_blank(),
#         plot.title = element_text(size = 12))
# 
# 
# incidence_map %>% 
#   filter(year == 2004,
#          cancer_type == "mal_brain_plus_glands",
#          sex == "all") %>% 
#   ggplot() +
#   geom_sf(aes(fill = value, geometry = geometry)) +
#   scale_fill_distiller(
#           limits = c(5, 11),
#           palette = "YlOrRd",
#           direction = 1) +
#   guides(colour = FALSE) +
#   labs(fill = "Crude Rate",
#         x = NULL,
#         y = NULL,
#        title = "Incidence, region, Malignant plus glands, 2004") +
#   theme(axis.text = element_blank(),
#         axis.ticks = element_blank(),
#         panel.background = element_blank(),
#         plot.title = element_text(size = 12))
# 
# incidence_map %>% 
#   filter(year == 2014,
#          cancer_type == "mal_brain_plus_glands",
#          sex == "all") %>% 
#   ggplot() +
#   geom_sf(aes(fill = value, geometry = geometry)) +
#   scale_fill_distiller(
#           limits = c(5, 11),
#           palette = "YlOrRd",
#           direction = 1) +
#   guides(colour = FALSE) +
#   labs(fill = "Crude Rate",
#         x = NULL,
#         y = NULL,
#        title = "Incidence, region, Malignant plus glands, 2014") +
#   theme(axis.text = element_blank(),
#         axis.ticks = element_blank(),
#         panel.background = element_blank(),
#         plot.title = element_text(size = 12))
# 
# 
# incidence_map %>% 
#   filter(year == 2018,
#          cancer_type == "mal_brain_plus_glands",
#          sex == "all") %>% 
#   ggplot() +
#   geom_sf(aes(fill = value, geometry = geometry)) +
#   scale_fill_distiller(
#           limits = c(5, 11),
#           palette = "YlOrRd",
#           direction = 1) +
#   guides(colour = FALSE) +
#   labs(fill = "Crude Rate",
#         x = NULL,
#         y = NULL,
#        title = "Incidence, region, Malignant plus glands, 2018") +
#   theme(axis.text = element_blank(),
#         axis.ticks = element_blank(),
#         panel.background = element_blank(),
#         plot.title = element_text(size = 12))
```

```{r}
min(incidence_region_map$inc_region)
max(incidence_region_map$inc_region)
```

```{r}
incidence_region_map %>% 
  filter(year == 1994) %>% 
  ggplot() +
  geom_sf(aes(fill = inc_region, geometry = geometry)) +
  scale_fill_distiller(
          limits = c(5.5, 11),
          palette = "YlOrBr",
          direction = 1) +
  guides(colour = FALSE) +
  labs(fill = "Crude Rate",
        x = NULL,
        y = NULL,
       title = "1994") +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(size = 12))

incidence_region_map %>% 
  filter(year == 2006) %>% 
  ggplot() +
  geom_sf(aes(fill = inc_region, geometry = geometry)) +
  scale_fill_distiller(
          limits = c(5.5, 11),
          palette = "YlOrBr",
          direction = 1) +
  guides(colour = FALSE) +
  labs(fill = "Crude Rate",
        x = NULL,
        y = NULL,
       title = "2006") +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(size = 12))


incidence_region_map %>% 
  filter(year == 2018) %>% 
  ggplot() +
  geom_sf(aes(fill = inc_region, geometry = geometry)) +
  scale_fill_distiller(
          limits = c(5.5, 11),
          palette = "YlOrBr",
          direction = 1) +
  guides(colour = FALSE) +
  labs(fill = "Crude Rate",
        x = NULL,
        y = NULL,
       title = "2018") +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(size = 12))
```

```{r}
incidence_region_map %>% 
  filter(year == 2018) %>% 
  ggplot() +
  geom_sf(aes(fill = region_flag, geometry = geometry)) +
  scale_fill_manual(
          values = c("north" = "#FF5722", "west" = "#132B43", "southeast" = "#56B1F7"),
          labels = c("North", "South-East", "West")) +
  guides(colour = FALSE) +
  labs(fill = "Region",
        x = NULL,
        y = NULL) +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(size = 12))
```

